on:
  push:
    branches: ["master"]
    paths: ["python/**"]

jobs:
  pypi-publish:
    # there should be a tag
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/python-v')

    name: Upload release to PyPI
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/purehtml-purescraps
    permissions:
      id-token: write # IMPORTANT: this permission is mandatory for trusted publishing
    steps:
      # retrieve your distributions here

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
